### PR TITLE
Perform step 1 calculations in Glicko functions

### LINKED ISSUE #3: `glicko_rating_period` is probably supposed to imply `decay_deviation`
As far as I understand it, Glicko paper requires to increase RD at the beginning of every rating period in Step 1 before changing it again in Step 2, regardless of whether the player played games in previous rating period or not, since it is said that Step 1 should be done for each player and Step 2 specifies RD as a rating deviation from Step 1:
> Step 1. Determine the rating and RD for each player at the start of the new rating period based on their rating and RD at the end of the previous period.

> [In Step 2] Assume that the player’s pre-period rating is r, and the ratings deviation is RD determined from Step 1.

Which I believe means that `glicko_rating_period` needs to run step 1 as well, the same equation that `decay_deviation` uses. This would be similar to Glicko-2 where Step 6 is ran in both `glicko2` and `glicko2_rating_period`.

### PR DESCRIPTION
**Pull request by asyncth**
This fixes an issue which caused Glicko functions such as `glicko` and `glicko_rating_period` not to perform calculations from the step 1 of the original Glicko paper. Those calculations are used to increase the rating deviation at the beginning of every rating period.

Fixes #3.

The results between `test_glicko_rating_period` and `test_glicko` are not exactly as similar as the comment on line 523 says they should be, someone probably should check carefully to make sure I didn't mess anything up.

Formatting changes were done by `rustfmt`.

### CODE REVIEW

**Comment by atomflunder** [comment]
Thanks again for the PR!

If I understood the glicko paper correctly, the `pre_deviation` as you called it needs to be inserted into the `g_value` functions in both the `glicko` and `glicko_rating_period` functions, instead of the `old_deviation`.

**Comment by asyncth** [comment]
I believe `RD` in `g` function refers to that `RD` argument that you see in `g`'s definition, you can see opponent's RD `RD_j` being passed into `g`  function in `d^2`'s definition as well

**Comment by asyncth** [comment]
Oh wait, nevermind, I was thinking about `glicko_rating_period`

**Comment by asyncth** [comment]
The paper doesn't seem to make it clear whether opponents' RD values are supposed to be pre-step1 or post-step1. If it's the latter, this would be more complicated that I thought. If that's the case, `glicko_rating_period` probably should calculate `pre_deviation` for opponents just to use it in those `g_value` calculations and then throw away, which kind of seems like a hack but should work.

**Comment by atomflunder** [comment]
If I understand this line in the paper correctly:

> Let the pre-period ratings of the m opponents (again from Step 1)
be r1, r2, . . . , rm and the ratings deviations be RD1, RD2, . . . , RDm.

This *should* mean the RDj in the calculations are the pre-period RD of the opponent, and so we do not need to calculate the `pre_deviation` of the opponent, but only the player. But I am not 100% sure. What do you think?

**Comment by asyncth** [comment]
This is actually one of my first confusions that I had after I first read this paper. After reading the text before the step 1 I was left with an impression that rating and deviation are calculated twice per rating period, once in the beginning and once in the end. After reading both of the steps, I wasn't sure if those calculations are supposed to be at the beginning or at the end of a rating period, so I decided to re-read both of the steps and pay more attentions to phrases like "at the end of previous period" and "pre-period". However, this didn't resolve my confusion and at that time for some reason I thought the information introduced by those phrases was conflicting with each other. After looking at some Glicko-2 implementations I concluded that rating and deviation are probably calculated only once in the rating period, when one rating period ends and another one begins.

I'm still not really sure what pre-period actually means, so I can't really tell if that means we need to calculate `pre_deviation` of opponents, I'm just going to do what you said. That means passing `pre_deviation` into `g_value` in `glicko`, but not in `glicko_rating_period`, right?

**Comment by asyncth** [comment]
Since Glicko-2 doesn't use modified opponent RDs, I'm inclined to believe what you said is correct.

**Comment by atomflunder** [comment]
> That means passing pre_deviation into g_value in glicko, but not in glicko_rating_period, right?

I think we should keep both functions "compatible" so that if you were to pass in a single game into `glicko_rating_period` it would produce the same result as `glicko`. And I looked into a Java implementation of Glicko/Glicko-2 and they do it like the way it is right now in your PR, having the "old deviation" in the g-calculations instead of the "pre deviation". So to be honest I think leaving it like this is fine.

**Comment by asyncth** [comment]
> This should mean the RDj in the calculations are the pre-period RD of the opponent, and so we do not need to calculate the `pre_deviation` of the opponent, but only the player.

Actually, if this is correct, doesn't that mean that there is no need to calculate `pre_deviation` in both `glicko` and `glicko_rating_period` because in both of them only opponent deviations are passed to `g_value`?

**Comment by asyncth** [comment]
So I guess we're leaving this as is? The difference between results on lines 670 and 671 seems to be pretty large, this is normal, right?

**Comment by atomflunder** [comment]
> So I guess we're leaving this as is? The difference between results on lines 670 and 671 seems to be pretty large, this is normal, right?

Might be because the value of 41 could be just unrealistically low, with the proper calculations, and it adjusts upwards.

After reading the paper carefully again, I think this should look correct. What do you think?  
Sorry that this was much more confusing than expected.

**Comment by asyncth** [comment]
I think it's correct, but the difference might be large because of default c = 63.2, after all in the paper this number was calculated with an assumptions that typical RD is 50, ratings periods last two months and it takes 5 years for player's rating to become as unreliable as initial rating, while my value 23.75 that I usually use was calculated with assumptions 50, one week and 3 years respectively.

Merge if you're OK with this PR, I'm fine with it.

**Pull request merged**
